version: '3'
services:
  freqtrade:
    image: frostaura/plutus
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "/share/Container/container-volume-data/Configuration/plutus/user_data:/freqtrade/user_data"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy FrostAura01Strategy
